language: rust
rust: stable
cache: cargo
sudo: false
os:
- linux

before_script:
  - rustc --version --verbose
  - cargo install cargo-travis --force
  - pip install 'travis-cargo<0.2' --user && export PATH=$HOME/.local/bin:$PATH

#RUST_LOG=scaproust,test 
#RUST_TEST_THREADS=1 
script:
  - cargo test && cargo doc --no-deps

after_success:
  - travis-cargo doc-upload
  - cargo coveralls
    
env:
  global:
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""
    - secure: T1UNJWD18XiBiv3s3HqTevdCztyOzuTVMjFKJOt9qPOjX7L3jrgk9lmlZpAxtB1dSVL3zOrH3S2N3mX970oXPb40WCuZGDNOVskyW94nszwNomqoV5C+0RC3jeowhqiHe1uocu42JidVhOWoQ4ciNff7mXjlFY70M9RnAaYJmk2QcqFFFmAVp7sei7zUF3bHSiwst99RlPHoMscH9hLqOGPaCIJ1x7pyvGdypFokFSzEtKoJJQ+y4LevI7CDUhVqqMkzGrW0q1nX5NYNxvygv2rP+N5HUzJcMnUhZN9LgRsxbEOi1/zygwASnWbLI35RhYwOSa0MuYsHOiDpErMWGZuEAf/z/QW2EGSm4rjUP26m4nMAu5TpoPDwK76TaLZ+C90C4SdEFpf6tgW3f/7gxTkFpZEfq9m7tIO4p0byl9XFxeOZHPgjxLRmhtgD7lI5QebSXU6UNgnDqq+L2BkFfOrA29IGm0j17EEWgEpYmrFVPEQb/9kJUW0acsYDBsUGmiB+0gVeZCtPMMk1Bmxtv8cmvRZnfKcLdCiqx6ai5Le7qcayJ+VzuxeFPQTQe6XPX4GM3KsuSSxZD51Jpf6i89DzR/Zn5HayJ/6PKwb7fQt014Jc3yxVhCZ08OcKm0svl17Eo6XYMe2S29AL7CjF0KwmdZQk8DHo+vpHPemIut4=

addons:
  apt:
    packages:
#      - libiberty-dev
      - libssl-dev
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev
      - elfutils
    sources:
      - kalakris-cmake
