[package]
name          = "scaproust"
version       = "0.2.0"
authors       = ["blabaere <benoit.labaere@gmail.com>"]
description   = "Nanomsg scalability protocols implementation in rust"
readme        = "README.md"
keywords      = ["io", "nanomsg", "messaging"]
license       = "MIT/Apache-2.0"
documentation = "https://blabaere.github.io/scaproust"
homepage      = "https://github.com/blabaere/scaproust"
repository    = "https://github.com/blabaere/scaproust"
exclude       = [
  ".gitignore",
  ".travis.yml",
  "appveyor.yml",
  "test/**/*",
]

[dependencies]
log = "0.3.6"
byteorder = "0.5.3"
time = "0.1.35"
clippy = "0.0.90"
mio = "0.6.0"
mio-uds = "0.6.0"

[target.'cfg(windows)'.dependencies]
miow = "0.1.3"

[dev-dependencies]
env_logger = "0.3.4"
stainless = "0.1.7"

[[test]]
name = "test"
path = "test/test.rs"
