version: 2
jobs:
  build:
    docker:
      - image: debian:stretch
    steps:
      - checkout
      - run:
        name: Install rust
        command: curl https://sh.rustup.rs -sSf | sh
      - run:
        name: Display rust version
        command: rustc --version --verbose
      - run:
        name: Build & Test
        command: cargo test && cargo doc --no-deps
