version: 2
jobs:
  build:
    docker:
      - image: abronan/rust-circleci:latest
    steps:
      - checkout
      - restore_cache:
          key: project-cache
      - run:
          name: Build & Test
          command: rustup run stable cargo test
